use std::{
    env, fs,
    path::{Path, PathBuf},
    process::Command,
};

const WASM_CURRENT_PATH: &str = "../../../web/vendor/iroh/current.txt";
const WEB_ROOT: &str = "../../../web";

fn main() {
    println!("cargo:rerun-if-changed=../../../.git/HEAD");
    println!("cargo:rerun-if-changed=../../../.git/index");
    println!("cargo:rerun-if-changed=../../../.git/refs/heads");
    println!("cargo:rerun-if-changed=../../../.git/packed-refs");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=Cargo.toml");
    println!("cargo:rerun-if-changed=src");

    let wasm_version = fs::read_to_string(WASM_CURRENT_PATH)
        .unwrap_or_else(|error| panic!("reading {WASM_CURRENT_PATH}: {error}"));
    let wasm_version = wasm_version.trim();
    assert!(
        wasm_version.len() == 64
            && wasm_version
                .bytes()
                .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte)),
        "{WASM_CURRENT_PATH} must contain a lowercase full SHA-256"
    );
    println!("cargo:rerun-if-changed={WASM_CURRENT_PATH}");
    println!("cargo:rerun-if-changed=../../../web/vendor/iroh/{wasm_version}");
    println!("cargo:rustc-env=DOGGYPILE_WASM_VERSION={wasm_version}");

    generate_web_asset_catalog(wasm_version);

    let sha = git_output_text(&["rev-parse", "--short=12", "HEAD"])
        .map(|text| text.trim().to_string())
        .filter(|text| !text.is_empty())
        .unwrap_or_else(|| "unknown".to_string());

    let dirty_hash = dirty_tree_hash();
    let build_git = match dirty_hash {
        Some(hash) => format!("{sha}-dirty.{hash:016x}"),
        None => sha,
    };
    println!("cargo:rustc-env=DOGGYPILE_BUILD_GIT={build_git}");
}

fn generate_web_asset_catalog(wasm_version: &str) {
    println!("cargo:rerun-if-changed={WEB_ROOT}");
    let root =
        fs::canonicalize(WEB_ROOT).unwrap_or_else(|error| panic!("finding {WEB_ROOT}: {error}"));
    let mut files = Vec::new();
    collect_production_assets(&root, &root, wasm_version, &mut files);
    files.sort_by(|left, right| left.0.cmp(&right.0));

    let mut generated = String::from("// @generated by build.rs; do not edit.\n&[\n");
    for (route, path) in files {
        generated.push_str(&format!(
            "    ({:?}, include_bytes!({:?}) as &'static [u8]),\n",
            format!("/{route}"),
            path.to_string_lossy(),
        ));
    }
    generated.push_str("]\n");
    let output =
        PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR")).join("web_assets_catalog.rs");
    fs::write(&output, generated)
        .unwrap_or_else(|error| panic!("writing {}: {error}", output.display()));
}

fn collect_production_assets(
    root: &Path,
    directory: &Path,
    wasm_version: &str,
    files: &mut Vec<(String, PathBuf)>,
) {
    let mut entries: Vec<_> = fs::read_dir(directory)
        .unwrap_or_else(|error| panic!("reading {}: {error}", directory.display()))
        .map(|entry| entry.expect("reading web directory entry"))
        .collect();
    entries.sort_by_key(|entry| entry.file_name());

    for entry in entries {
        let path = entry.path();
        let relative = path.strip_prefix(root).expect("asset beneath web root");
        let route = relative.to_string_lossy().replace('\\', "/");
        if excluded_from_production(&route, wasm_version) {
            continue;
        }
        if path.is_dir() {
            collect_production_assets(root, &path, wasm_version, files);
        } else if path.is_file() {
            files.push((route, path));
        }
    }
}

fn excluded_from_production(route: &str, wasm_version: &str) -> bool {
    let components: Vec<_> = route.split('/').collect();
    let name = components.last().copied().unwrap_or_default();
    if name == "mock.js"
        || name == "app.js.bak"
        || name.ends_with(".bak")
        || name.ends_with(".backup")
        || name.ends_with('~')
        || components
            .iter()
            .any(|part| matches!(*part, "test" | "tests" | "__tests__" | "backup" | "backups"))
    {
        return true;
    }

    if components.get(0..2) == Some(&["vendor", "iroh"]) {
        if let Some(version) = components.get(2) {
            let version_like =
                version.len() == 64 && version.bytes().all(|byte| byte.is_ascii_hexdigit());
            return version_like && *version != wasm_version;
        }
    }
    false
}

fn dirty_tree_hash() -> Option<u64> {
    let mut bytes = Vec::new();
    bytes.extend(git_output(&["diff", "HEAD", "--binary"])?);
    bytes.extend(git_output(&[
        "status",
        "--porcelain=v1",
        "--untracked-files=all",
    ])?);
    (!bytes.is_empty()).then(|| fnv1a64(&bytes))
}

fn git_output_text(args: &[&str]) -> Option<String> {
    String::from_utf8(git_output(args)?).ok()
}

fn git_output(args: &[&str]) -> Option<Vec<u8>> {
    let output = Command::new("git").args(args).output().ok()?;
    output.status.success().then_some(output.stdout)
}

fn fnv1a64(bytes: &[u8]) -> u64 {
    let mut hash = 0xcbf29ce484222325u64;
    for byte in bytes {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(0x100000001b3);
    }
    hash
}
